<template>
  <div class="dashboard">
    <section class="dashboard-hero"><div><p class="eyebrow">YOUR WORKSPACE</p><h1>Welcome back, {{ displayName }}.</h1><p>Ready to translate? Open the live camera when you want to recognise a hand sign.</p><router-link class="start-translation" to="/translate"><i class="bi bi-camera-video"></i> Start live translation <i class="bi bi-arrow-right"></i></router-link></div><div class="hero-visual"><div class="visual-icon"><i class="bi bi-hand-index-thumb"></i></div><span>Recognition ready</span><strong>7 supported signs</strong></div></section>
    <section class="cards"><BaseCard title="Live translator" value="Ready" subtitle="Open your camera when needed" icon="bi bi-camera-video" /><BaseCard title="Supported signs" value="7" subtitle="Common hand gestures" icon="bi bi-hand-index-thumb" /><BaseCard title="Voice output" :value="settings.voice ? 'On' : 'Off'" subtitle="Manage in Settings" icon="bi bi-volume-up" /><BaseCard title="Your profile" value="Active" subtitle="Keep your details up to date" icon="bi bi-person-check" /></section>
    <section class="next-steps"><div><p class="eyebrow">QUICK GUIDE</p><h2>How it works</h2></div><div class="steps"><article><span>01</span><i class="bi bi-camera-video"></i><h3>Open Translate</h3><p>Go to the live translator page and allow camera access.</p></article><article><span>02</span><i class="bi bi-hand-index-thumb"></i><h3>Show a sign</h3><p>Keep one supported hand gesture clear and steady.</p></article><article><span>03</span><i class="bi bi-chat-square-text"></i><h3>Read or listen</h3><p>See the result immediately and use voice output if needed.</p></article></div></section>
  </div>
</template>
<script setup>
import { computed } from 'vue'
import BaseCard from '../components/BaseCard.vue'
import { useAuth } from '../composables/useAuth.js'
import { useSettings } from '../composables/useSettings.js'
const { user } = useAuth()
const { settings } = useSettings()
const displayName = computed(() => user.value.name || user.value.email?.split('@')[0] || 'there')
</script>
<style scoped>
.dashboard{max-width:1380px;margin:0 auto;padding:10px 4px 34px}.dashboard-hero{display:grid;grid-template-columns:1.4fr .6fr;gap:30px;align-items:center;padding:38px 44px;border-radius:28px;color:#fff;background:radial-gradient(circle at 90% 20%,#3b82f6 0,transparent 32%),linear-gradient(135deg,#0f172a,#172554)}.eyebrow{margin:0 0 8px;color:#93c5fd;font-size:.74rem;font-weight:800;letter-spacing:.13em}.dashboard-hero h1{margin:0;font-size:clamp(2rem,4vw,3rem);letter-spacing:-.04em}.dashboard-hero p:not(.eyebrow){max-width:620px;margin:12px 0 24px;color:#cbd5e1;line-height:1.6}.start-translation{display:inline-flex;align-items:center;gap:10px;padding:13px 17px;border-radius:13px;background:#fff;color:#1e3a8a;font-weight:800;text-decoration:none}.hero-visual{display:grid;place-items:center;justify-items:center;gap:8px;padding:24px;border:1px solid rgba(255,255,255,.17);border-radius:20px;background:rgba(255,255,255,.08)}.visual-icon{display:grid;place-items:center;width:70px;height:70px;border-radius:22px;background:#fff;color:#2563eb;font-size:2rem}.hero-visual span{color:#bfdbfe;font-size:.85rem}.hero-visual strong{font-size:1.1rem}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:22px 0 32px}.next-steps{padding:28px;border:1px solid #e2e8f0;border-radius:24px;background:#fff}.next-steps .eyebrow{color:#2563eb}.next-steps h2{margin:0;color:#0f172a}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:22px}.steps article{position:relative;padding:22px;border-radius:18px;background:#f8fafc}.steps article>span{position:absolute;right:18px;top:17px;color:#94a3b8;font-size:.78rem;font-weight:800}.steps i{display:grid;place-items:center;width:42px;height:42px;border-radius:13px;background:#dbeafe;color:#2563eb;font-size:1.2rem}.steps h3{margin:17px 0 6px;font-size:1rem}.steps p{margin:0;color:#64748b;line-height:1.55;font-size:.9rem}@media(max-width:1000px){.cards{grid-template-columns:repeat(2,1fr)}}@media(max-width:720px){.dashboard-hero{grid-template-columns:1fr;padding:28px}.hero-visual{display:none}.cards,.steps{grid-template-columns:1fr}.next-steps{padding:20px}}
</style>
