<template>
  <section class="hero">
    <div class="hero-content">
      <p class="eyebrow"><i class="bi bi-sparkles"></i> Accessible communication, made simpler</p>
      <h1>Understand every <span>hand sign</span> in real time.</h1>
      <p class="hero-copy">A clean, camera-powered workspace for recognising supported hand gestures and turning them into clear text.</p>
      <div class="buttons"><router-link class="primary-action" to="/register">Get started <i class="bi bi-arrow-right"></i></router-link><router-link class="secondary-action" to="/login">Sign in</router-link></div>
      <div class="trust-row"><span><i class="bi bi-camera-video"></i> Live camera</span><span><i class="bi bi-lightning-charge"></i> Instant results</span><span><i class="bi bi-shield-check"></i> Private session</span></div>
    </div>
    <div class="hero-visual" aria-hidden="true"><div class="visual-glow"></div><div class="camera-window"><div class="camera-top"><span></span><span></span><span></span><strong>LIVE</strong></div><div class="hand-icon">🤟</div><div class="result-pill"><i class="bi bi-check-circle-fill"></i><div><small>Detected sign</small><strong>I love you</strong></div><b>96%</b></div></div></div>
  </section>
</template>
<style scoped>
.hero{display:grid;grid-template-columns:1.05fr .95fr;gap:40px;align-items:center;max-width:1280px;min-height:580px;margin:22px auto 0;padding:64px;overflow:hidden;border-radius:32px;color:#fff;background:radial-gradient(circle at 90% 15%,#2563eb 0,transparent 31%),linear-gradient(135deg,#0f172a,#172554)}.eyebrow{margin:0 0 18px;color:#bfdbfe;font-weight:700;font-size:.8rem;letter-spacing:.08em;text-transform:uppercase}.hero h1{max-width:650px;margin:0;font-size:clamp(2.6rem,5vw,4.5rem);line-height:1.05;letter-spacing:-.05em}.hero h1 span{color:#93c5fd}.hero-copy{max-width:570px;margin:23px 0 30px;color:#cbd5e1;font-size:1.08rem;line-height:1.7}.buttons{display:flex;gap:12px;flex-wrap:wrap}.primary-action,.secondary-action{display:inline-flex;align-items:center;gap:10px;padding:14px 20px;border-radius:14px;text-decoration:none;font-weight:800}.primary-action{color:#1e3a8a;background:#fff}.secondary-action{color:#fff;border:1px solid rgba(255,255,255,.25)}.trust-row{display:flex;gap:16px;flex-wrap:wrap;margin-top:38px;color:#cbd5e1;font-size:.82rem}.trust-row i{margin-right:4px;color:#93c5fd}.hero-visual{position:relative;min-height:400px;display:grid;place-items:center}.visual-glow{position:absolute;width:300px;height:300px;background:#60a5fa;border-radius:50%;filter:blur(90px);opacity:.35}.camera-window{position:relative;width:min(100%,400px);padding:16px;border:1px solid rgba(255,255,255,.22);border-radius:25px;background:rgba(15,23,42,.38);box-shadow:0 30px 80px rgba(0,0,0,.32)}.camera-top{display:flex;align-items:center;gap:6px}.camera-top span{width:8px;height:8px;border-radius:50%;background:#94a3b8}.camera-top strong{margin-left:auto;padding:5px 8px;border-radius:20px;background:rgba(239,68,68,.25);color:#fecaca;font-size:.65rem;letter-spacing:.08em}.hand-icon{display:grid;place-items:center;height:270px;margin:14px 0;border-radius:17px;font-size:8rem;background:linear-gradient(135deg,#1d4ed8,#0f172a)}.result-pill{display:flex;align-items:center;gap:10px;padding:12px;border-radius:15px;background:#fff;color:#0f172a}.result-pill>i{color:#22c55e}.result-pill small,.result-pill strong{display:block}.result-pill small{color:#64748b;font-size:.68rem}.result-pill b{margin-left:auto;color:#15803d;font-size:.8rem}@media(max-width:900px){.hero{grid-template-columns:1fr;padding:38px 26px;min-height:0}.hero-visual{min-height:320px}.camera-window{max-width:350px}.hand-icon{height:205px}}@media(max-width:520px){.hero{margin:0;border-radius:0;padding:40px 22px}.trust-row{gap:10px}.hero-visual{display:none}}
</style>
